const login = require('./routes/login')
const signup = require('./routes/signup')
const isAuth = require('./middlewares/auth')
const express = require('express')
const app = express()

app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.get('/ping', async (_, res) => res.json({"msg": "pong"}))
app.get('/', isAuth, async (_, res) => res.json({"msg": "Welcome home!"}))
app.use('/login', login)
app.use('/signup', signup)
app.listen(3000, () => console.log('Listening on port 3000'))
